FROM python:slim
FROM nginx

COPY --from=0 /usr/local/bin /usr/local/bin
COPY --from=0 /usr/local/lib /usr/local/lib

COPY ./python/NginxCheck /app/NginxCheck
COPY ./default_all.conf.template /etc/nginx/templates/default.conf.template

ENV INPUT_SOCKET "/sockets/input/nginx.sock"
ENV OUTPUT_SOCKET "/sockets/output/nginx.sock"
ENV BASE_PASS "/count"

COPY ./python/app_all.py /app/app.py

CMD ["python", "-u", "/app/app.py"]

COPY ./.htpasswd "/etc/nginx/"
COPY ./includes/ "/etc/nginx/includes/"
COPY ./python/GetAllowedCidr/ "/app/GetAllowedCidr"

ENV IPLIST_FILE_PATH "/iplist/iplist"
ENV BASIC_NAME "Auth"
ENV BASIC_CHECK "True"
ENV IP_CHECK "True"
ENV ALLOWED_COUNTRIES "JP"
